name: 'CycloneDX Node.js Generate SBOM'
author: Patrick Dwyer
description: 'Github action to generate a CycloneDX BOM for Node.js projects'
inputs:
  path:
    description: 'The path to a Node.js project'
    default: ./
    required: false
  json:
    description: 'Produce a JSON BOM instead of XML, set to any value instead of false (default)'
    default: 'false'
    required: false
  output:
    description: 'Output filename'
    default: ./bom.xml
    required: false
runs:
  using: 'node12'
  main: 'index.js'
